routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('posts', 'PostController');
Route::resource('users', 'UserController');
Route::resource('roles', 'RoleController');
Route::resource('permissions','PermissionController');
Route::resource('categorys','Admin\AdminCategoryController');
Route::resource('products','ProductsController');
Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');
Route::get('/','ViewProductController@getView');
Route::get('/post/{id}','ViewProductController@getPost');
Route::get('/about',function (){
    return view('frontend.about');
});
Route::get('/contact',function (){
    return view('frontend.contact');
});
Route::get('/test', function ()
{
    return view('quanly/index');
});
Route::get('/test1', function ()
{
    return view('quanly/test');
});

Route::get('test2', 'DataController@getStudent');
Route::get('data2', 'DataController@dataStudent');
Route::get('test3', 'DataController@getCourse');
Route::get('data3', 'DataController@dataCourse');

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    //

    protected $fillable = ['name', 'alias', 'price', 'intro', 'content', 'image','keywords','description','user_id','cate_id'];
    public $timestamps= false;

    public function categories()
    {
        return $this->belongsTo('App\Category');
    }
    public function user()
    {
        return $this->belongsTo('App\User');
    }
    public function ProductImage()
    {
        return $this->belongsTo('App\ProductImage');
    }
}

app/Http/Controllers/ProductsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Product;

use App;
use Illuminate\Support\Facades\Config;

class ProductsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
    {
        $this->middleware(['auth']);
    }

    public function index()
    {
        //
        $products = Product::all();

        return view('products.index')->with('products',$products);
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $categories =  App\Category::all();

        return view('products.create')->with('categories',$categories);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $this->validate($request, [
            'name'   => 'required|max:255',
            'price'  => 'required',
             'into'  => 'required',
              'image' => 'image|mimes:jpg,png',
        ]);



    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/products/create.blade.php
{{-- \resources\views\users\index.blade.php --}}
@extends('layouts.app')

@section('title', '| Users')

@section('content')

    @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    {{ Form::open(array('url' => 'products','enctype' =>'multipart/form-data')) }}
    <div class="form-group">
        {{ Form::label('name', 'Name') }}
        {{ Form::text('name', null, array('class' => 'form-control')) }}
    </div>
    <div class="form-group">
        {{ Form::label('price', 'Price') }}
        {{ Form::text('price', null, array('class' => 'form-control')) }}

    </div>
    <div class="form-group">
        {{ Form::label('name', 'Category') }}
        <select class="form-control">
            @foreach($categories as $category)
                <option>{{$category->name}}</option>
            @endforeach
        </select>



    </div>
    <div class="form-group">
        {{ Form::label('Content', 'Name') }}
        <textarea name="into" cols="30" rows="10" class="form-control"></textarea>
    </div>
    <div class="form-group">
        {{ Form::label('image', 'Image') }}
        <br>
        {{ Form::file('image') }}
    </div>

    {{ Form::submit('Add', array('class' => 'btn btn-primary')) }}


@endsection

resources/views/products/index.blade.php
{{-- \resources\views\users\index.blade.php --}}
@extends('layouts.app')

@section('title', '| Users')

@section('content')

    <div class="col-lg-10 col-lg-offset-1">
        <h1><i class="fa fa-users"></i> Products <a href="{{ route('products.index') }}" class="btn btn-default pull-right">Roles</a>
            <a href="{{ route('permissions.index') }}" class="btn btn-default pull-right">Permissions</a></h1>
        <hr>
        <div class="table-responsive">
            <table class="table table-bordered table-striped">

                <thead>
                <tr>
                    <th>ID</th>
                    <th>Name</th>
                    <th>Info</th>
                    <th>Context</th>
                    <th>price</th>
                    <th>Image</th>
                    <th>Actions</th>
                </tr>
                </thead>

                <tbody>

                @foreach ($products as $product)
                    <tr>

                        <td>{{ $product->id    }}</td>
                        <td>{{ $product->name  }}</td>
                        <td>{{ $product->intro }}</td>
                        <td>{{ $product->content  }}</td>
                        <td>{{ $product->price }}</td>
                        <td><img src="{{$product->image}}" alt=""></td>

                        <td>
                            <a href="{{ route('users.edit', $product->id) }}" class="btn btn-info pull-left" style="margin-right: 3px;">Edit</a>

                            {!! Form::open(['method' => 'DELETE', 'route' => ['users.destroy', $product->id] ]) !!}
                            {!! Form::submit('Delete', ['class' => 'btn btn-danger']) !!}
                            {!! Form::close() !!}

                        </td>
                    </tr>
                @endforeach
                </tbody>

            </table>
        </div>

        <a href="{{ route('products.create') }}" class="btn btn-success">Add User</a>

    </div>

@endsection